---
# This playbook executes tasks on PSB components such as MQ and IIB. 
# Tasks include installation, verification, configuration, uninstallation.
# The list of executable tasks are within the role folders.
# The execution of specific tasks e.g. installation are controlled using the tags mechanism of Ansible.

- name: MQ tasks
  import_playbook: psbmq.yml

- name: IIB tasks
  import_playbook: psbiib.yml
